name: Script tests

on: [push]

jobs:
  tests:
    name: Script test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt install v4l-utils
        sudo apt install fswebcam
    - name: Testing correct password
      run: |
        chmod +x test_registration.sh
        ./test_registration.sh
